# Generated by Django 5.2.8 on 2025-11-20 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='cities/')),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('document', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'enterprise',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('document', models.CharField(max_length=30, unique=True)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'passenger',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('P', 'Pix'), ('M', 'Money'), ('C', 'Card'), ('O', 'Other')], max_length=1)),
                ('payment_status', models.CharField(choices=[('D', 'Done'), ('W', 'Waiting'), ('C', 'Canceled')], max_length=1)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Harbor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.PROTECT, related_name='harbors', to='core.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(db_column='id_payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.payment')),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arrival_harbor', models.ForeignKey(db_column='id_arrival_harbor', on_delete=django.db.models.deletion.PROTECT, related_name='arriving_trips', to='core.harbor')),
                ('departure_harbor', models.ForeignKey(db_column='id_departure_harbor', on_delete=django.db.models.deletion.PROTECT, related_name='departing_trips', to='core.harbor')),
            ],
            options={
                'db_table': 'trip',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TripSegment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('trip', models.ForeignKey(db_column='id_trip', on_delete=django.db.models.deletion.PROTECT, related_name='trip_segments', to='core.trip')),
            ],
            options={
                'db_table': 'trip_segment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type_of_accommodation', models.CharField(choices=[('I', 'Individual'), ('C', 'Cabin')], max_length=1)),
                ('cart', models.ForeignKey(db_column='id_cart', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.cart')),
                ('passenger', models.ForeignKey(db_column='id_passenger', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.passenger')),
                ('trip_segment', models.ForeignKey(db_column='id_trip_segment', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.tripsegment')),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('stop_datetime', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('harbor', models.ForeignKey(db_column='id_harbor', on_delete=django.db.models.deletion.PROTECT, related_name='harbors', to='core.harbor')),
                ('trip', models.ForeignKey(db_column='id_trip', on_delete=django.db.models.deletion.PROTECT, related_name='trip_stops', to='core.trip')),
            ],
            options={
                'db_table': 'trip_stop',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='from_stop',
            field=models.ForeignKey(db_column='id_from_stop', on_delete=django.db.models.deletion.PROTECT, related_name='from_stop', to='core.tripstop'),
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='to_stop',
            field=models.ForeignKey(db_column='id_to_stop', on_delete=django.db.models.deletion.PROTECT, related_name='to_stop', to='core.tripstop'),
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='vessels/')),
                ('registry_code', models.CharField(max_length=50)),
                ('vessel_type', models.CharField(choices=[('B', 'Boat'), ('S', 'Speed Boat'), ('F', 'Ferry Boat')], max_length=1)),
                ('individual_capacity', models.IntegerField()),
                ('enterprise', models.ForeignKey(db_column='id_enterprise', on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='core.enterprise')),
            ],
            options={
                'db_table': 'vessel',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vessel',
            field=models.ForeignKey(db_column='id_vessel', on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.vessel'),
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('vessel', models.ForeignKey(db_column='id_vessel', on_delete=django.db.models.deletion.CASCADE, related_name='cabins', to='core.vessel')),
            ],
            options={
                'db_table': 'cabin',
                'managed': True,
            },
        ),
    ]
