# Generated by Django 5.2.8 on 2025-11-26 23:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='assets/cities/')),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('document', models.CharField(max_length=30, unique=True)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'passenger',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('P', 'Pix'), ('M', 'Money'), ('C', 'Card'), ('O', 'Other')], max_length=1)),
                ('payment_status', models.CharField(choices=[('D', 'Done'), ('W', 'Waiting'), ('C', 'Canceled')], max_length=1)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('fantasy_name', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='assets/enterprises/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Harbor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.PROTECT, related_name='harbors', to='core.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cart', models.OneToOneField(db_column='id_cart', on_delete=django.db.models.deletion.PROTECT, to='core.cart')),
                ('payment', models.OneToOneField(db_column='id_payment', on_delete=django.db.models.deletion.PROTECT, to='core.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type_of_accommodation', models.CharField(choices=[('I', 'Individual'), ('C', 'Cabin')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled')], default='Reserved', max_length=10)),
                ('main_passenger', models.ForeignKey(db_column='id_passenger', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.passenger')),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(db_column='id_cart', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.PROTECT, to='core.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssociatedPassenger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('passenger', models.ForeignKey(db_column='id_passenger', on_delete=django.db.models.deletion.PROTECT, to='core.passenger')),
                ('ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.PROTECT, related_name='associated_passengers', to='core.ticket')),
            ],
            options={
                'db_table': 'associated_passenger',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arrival_harbor', models.ForeignKey(db_column='id_arrival_harbor', on_delete=django.db.models.deletion.PROTECT, related_name='arriving_trips', to='core.harbor')),
                ('departure_harbor', models.ForeignKey(db_column='id_departure_harbor', on_delete=django.db.models.deletion.PROTECT, related_name='departing_trips', to='core.harbor')),
            ],
            options={
                'db_table': 'trip',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TripSegment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('individual_vacancies', models.IntegerField(default=0)),
                ('trip', models.ForeignKey(db_column='id_trip', on_delete=django.db.models.deletion.PROTECT, related_name='trip_segments', to='core.trip')),
            ],
            options={
                'db_table': 'trip_segment',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='trip_segment',
            field=models.ForeignKey(db_column='id_trip_segment', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.tripsegment'),
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('stop_datetime', models.DateTimeField()),
                ('number', models.DecimalField(decimal_places=2, max_digits=6)),
                ('harbor', models.ForeignKey(db_column='id_harbor', on_delete=django.db.models.deletion.PROTECT, related_name='harbors', to='core.harbor')),
                ('trip', models.ForeignKey(db_column='id_trip', on_delete=django.db.models.deletion.PROTECT, related_name='trip_stops', to='core.trip')),
            ],
            options={
                'db_table': 'trip_stop',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='from_stop',
            field=models.ForeignKey(db_column='id_from_stop', on_delete=django.db.models.deletion.PROTECT, related_name='from_stop', to='core.tripstop'),
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='to_stop',
            field=models.ForeignKey(db_column='id_to_stop', on_delete=django.db.models.deletion.PROTECT, related_name='to_stop', to='core.tripstop'),
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='assets/vessels/')),
                ('registry_code', models.CharField(max_length=50)),
                ('vessel_type', models.CharField(choices=[('B', 'Boat'), ('S', 'Speed Boat'), ('F', 'Ferry Boat')], max_length=1)),
                ('individual_capacity', models.IntegerField()),
                ('enterprise', models.ForeignKey(db_column='id_enterprise', on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='core.enterprise')),
            ],
            options={
                'db_table': 'vessel',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vessel',
            field=models.ForeignKey(db_column='id_vessel', on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.vessel'),
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('vessel', models.ForeignKey(db_column='id_vessel', on_delete=django.db.models.deletion.CASCADE, related_name='cabins', to='core.vessel')),
            ],
            options={
                'db_table': 'cabin',
                'managed': True,
            },
        ),
    ]
