# Generated by Django 5.2.8 on 2025-11-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedPassenger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('passenger', models.ForeignKey(db_column='id_passenger', on_delete=django.db.models.deletion.PROTECT, to='core.passenger')),
                ('ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.PROTECT, related_name='associated_passengers', to='core.ticket')),
            ],
            options={
                'db_table': 'associated_passenger',
                'managed': True,
            },
        ),
    ]
