# Generated by Django 5.2.8 on 2025-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Teste', max_length=50),
        ),
    ]
