# Generated by Django 5.2.8 on 2025-11-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='document',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_type',
            field=models.CharField(choices=[('Boat', 'Barco'), ('Speed Boat', 'Lancha'), ('Ferry Boat', 'Ferry Boat')], max_length=20),
        ),
    ]
