# Generated by Django 5.2.8 on 2025-11-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_cpf_alter_enterprise_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='number_of_cabins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_type',
            field=models.CharField(choices=[('BOAT', 'Barco'), ('SPEED_BOAT', 'Lancha'), ('FERRY_BOAT', 'Ferry Boat')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Cabin',
        ),
    ]
