# Generated by Django 5.2.8 on 2025-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vessel_number_of_cabins_alter_vessel_vessel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstop',
            name='number',
            field=models.IntegerField(default=-1),
        ),
    ]
