# Generated by Django 5.2.8 on 2025-12-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tripstop_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='assets/users/'),
        ),
    ]
