# Generated by Django 5.2.8 on 2025-12-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripstop',
            name='number',
        ),
        migrations.AddField(
            model_name='tripstop',
            name='number_of_lands',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='number_of_shipments',
            field=models.IntegerField(default=0),
        ),
    ]
