# Generated by Django 5.2.8 on 2025-12-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_tripstop_number_tripstop_number_of_lands_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='base_price',
            new_name='individual_base_price',
        ),
        migrations.AddField(
            model_name='trip',
            name='cabin_base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
