# Generated by Django 5.2.8 on 2025-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_base_price_trip_individual_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='is_arrival_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='is_departure_stop',
            field=models.BooleanField(default=False),
        ),
    ]
