# Generated by Django 5.2.8 on 2025-12-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tripstop_is_arrival_stop_tripstop_is_departure_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripsegment',
            name='individual_vacancies',
        ),
    ]
