# Generated by Django 5.2.8 on 2025-12-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_tripsegment_individual_vacancies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripsegment',
            old_name='price',
            new_name='individual_price',
        ),
    ]
