# Generated by Django 5.2.8 on 2025-12-05 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_price_tripsegment_individual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='main_passenger',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(db_column='id_passenger', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='trip',
            field=models.ForeignKey(db_column='id_trip', on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='core.trip'),
        ),
        migrations.DeleteModel(
            name='AssociatedPassenger',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
