# Generated by Django 5.2.8 on 2025-12-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_cart_user_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsegment',
            name='from_stop',
            field=models.ForeignKey(db_column='id_from_stop', on_delete=django.db.models.deletion.CASCADE, related_name='from_stop', to='core.tripstop'),
        ),
        migrations.AlterField(
            model_name='tripsegment',
            name='to_stop',
            field=models.ForeignKey(db_column='id_to_stop', on_delete=django.db.models.deletion.CASCADE, related_name='to_stop', to='core.tripstop'),
        ),
        migrations.AlterField(
            model_name='tripsegment',
            name='trip',
            field=models.ForeignKey(db_column='id_trip', on_delete=django.db.models.deletion.CASCADE, related_name='trip_segments', to='core.trip'),
        ),
    ]
