# Generated by Django 5.2.8 on 2025-12-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type_of_accommodation',
            field=models.CharField(choices=[('I', 'Individual'), ('C', 'Cabin')], default='I', max_length=1),
        ),
    ]
