# Generated by Django 5.2.8 on 2025-12-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_ticket_type_of_accommodation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripstop',
            old_name='number_of_lands',
            new_name='number_of_landings',
        ),
    ]
